import "dotenv/config";

export const ENV = {

USER_SIGNUP:process.env.NEXT_PUBLIC_BACKEND_USER_SIGNUP,
ADMIN_SIGNUP:process.env.NEXT_PUBLIC_BACKEND_ADMIN_SIGNUP,
SIGNIN:process.env.NEXT_PUBLIC_BACKEND_SIGNIN,
ADMIN_GET_MATCH:process.env.NEXT_PUBLIC_ADMIN_GET_MATCHES,
USER_SIGNOUT:process.env.NEXT_PUBLIC_BACKEND_USER_SIGNIN,
CREATE_MATCH:process.env.NEXT_PUBLIC_ADMIN_CREATE_MATCH,
COMMENTARY:process.env.NEXT_PUBLIC_ADMIN_CREATE_COMMENTARY,
HTTP_URL:process.env.NEXT_PUBLIC_BACKEND_HTTP_URL,
GET_COMMENTARY:process.env.NEXT_PUBLIC_ADMIN_GET_COMMENTARY,
USER_MATCH:process.env.NEXT_PUBLIC_USER_GET_MATCHES,
USER_DETAIL:process.env.NEXT_PUBLIC_USER_DETAIL,
WS_URL:process.env.NEXT_PUBLIC_WS_URL

}